config/routes.rb
Rails.application.routes.draw do
  get 'game/index'
  post 'game/fire_missile'
  get 'main/index'

  root 'main#index'

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

    if !params["username"].nil?
      session[:username] = params["username"]
    elsif session[:username].nil?
      session[:username] = "guest" 
    end

    @user = User.where(username: session[:username]).take
    if @user.nil?
      @user = User.create(username: session[:username])
    end

    @completed_games = Game.includes(:user_1)
                           .includes(:user_2)
                           .order(id: :desc)
                           .where.not(user_2_id: nil)
                           .where('user_1_id = ? OR user_2_id = ?', @user.id, @user.id)
                           .where.not(winner_id: nil)
    @user_unstarted_games = Game.where(user_1_id: @user.id, user_2_id: nil)
                                .includes(:user_1)
                                .order(id: :desc)
    @in_process_games = Game.includes(:user_1)
                           .includes(:user_2)
                           .order(id: :desc)
                           .where.not(user_2_id: nil)
                           .where('user_1_id = ? OR user_2_id = ?', @user.id, @user.id)
                           .where(winner_id: nil)
    @available_games = Game.where.not(user_1_id: @user.id)
                           .where(user_2_id: nil)
                           .includes(:user_1)
                           .order(id: :desc)
  end
end


# Game.includes(:user_1).includes(:user_2).order(id: :desc).where('user_1_id = ? OR user_2_id = ?', @user.id, @user.id).where(winner_id: nil)

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.erb
<div id="user-login-bar">
  <%= form_tag(root_path, :method => "get", id: "user-login-form") do %>
      Login as a different user:
      <%= text_field_tag :username, params[:username], placeholder: "Enter username", class: "user-login-box" %>
      <%= submit_tag "Login", :name => nil, class: "user-login-button" %>
  <% end %>
</div>

<div class="all-games">
<div>In process games:
  <ul>
    <% @in_process_games.each do |game| %>
      <li>
      <%= link_to "Game ##{game.id}", game_index_path(:game_id => game.id) %>
        vs <%= game.get_opponent(@user.id).username %>
      </li>
    <% end %>
  </ul>
</div>

<div>Available games:
  <ul>
    <% @available_games.each do |game| %>
      <li>
      <%= link_to "Game ##{game.id}", game_index_path(:game_id => game.id) %>
        vs <%= game.user_1.username %>
      </li>
    <% end %>
  </ul>
</div>

<div>Completed games:
  <ul>
    <% @completed_games.each do |game| %>
    <li>
      <%= link_to "Game ##{game.id}", game_index_path(:game_id => game.id) %>
        <b><%= game.winner_id == @user.id ? "Won" : "Lost" %> </b>vs <%= game.get_opponent(@user.id).username%>
    </li>
    <% end %>
  </ul>
</div>

<div>Your unstarted games:
  <ul>
    <% @user_unstarted_games.each do |game| %>
      <li><%= link_to "Game ##{game.id}", game_index_path(:game_id => game.id) %></li>
    <% end %>
  </ul>
</div>

<div id="new-game">
  <%= form_tag(game_index_path, :method => "get", id: "new-game-form") do %>
      <%= submit_tag "Begin new match", :name => nil, class: "begin-match-button" %>
  <% end %>
</div>
</div>