config/routes.rb
Rails.application.routes.draw do
  get 'game/index'
  post 'game/fire_missile'
  get 'main/index'

  root 'main#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  include ApplicationHelper
  belongs_to :user_1, :class_name => 'User'
  belongs_to :user_2, :class_name => 'User'
  belongs_to :winner, :class_name => 'User'
  belongs_to :next_turn_user, :class_name => 'User'

  def add_user(user_id)
    self.user_2_id = user_id
    self.save
  end

  def get_opponent(user_id)
    if user_id == self.user_1_id
      return self.user_2
    elsif user_id == self.user_2_id
      return self.user_1
    end

    return nil
  end

  def begin
    self.has_started = true
    self.next_turn_user_id = self.user_1_id
    self.save
  end

  def is_players_turn?(user)
    return self.has_started && self.next_turn_user_id == user.id
  end

  def switch_to_next_players_turn
    self.next_turn_user_id = self.next_turn_user_id == user_1_id ? user_2_id : user_1_id
    self.save
  end

  def is_over?
    return !winner_id.nil?
  end

  def update_winner(user)
    self.winner_id = user.id
    self.save
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  include ApplicationHelper

  def index
    @user = User.where(username: session[:username]).take
    if !params[:hit].nil?
      @hit = params[:hit] == "true"
    end
    
    if !params[:sunk].nil?
      @sunk = params[:sunk] == "true"
    end


    
    if params[:game_id].nil?
      @game = Game.create(user_1_id: @user.id)
      params[:game_id] = @game.id
      return
    end

    @game = Game.find(params[:game_id])
    if !@game.has_started && @user.id != @game.user_1_id
      @game.add_user(@user.id)
      @game.begin
      Board.create_new_boards(@game)
    end

    if @game.has_started
      if @user.id != @game.user_1_id && @user.id != @game.user_2_id
        render :partial => "game/incorrect_user"
        return
      end

      # Defined in ApplicationHelper
      game_cache = ApplicationController.helpers.get_cache(@game.id)

      @player_board = game_cache[@user.id]
      @opponent_user = @game.get_opponent(@user.id)
      @opponent_board = game_cache[@opponent_user.id]
      @total_ships = Ship.count
      @last_move = Hash.new
      @last_move[@user.id] = ApplicationController.helpers.get_last_move(@game.id, @user.id)
      @last_move[@opponent_user.id] = ApplicationController.helpers.get_last_move(@game.id, @opponent_user.id)
    end
  end

  def fire_missile
    @user = User.where(username: session[:username]).take
    tile = Board.find(params[:tile_id])
    game = tile.game
    
    if game.next_turn_user_id != @user.id
      redirect_to game_index_path(game_id: tile.game_id)
      return
    end

    tile.mark_as_bombed
    hit = tile.ship_exists?
    sunk = tile.ship_sunk?

    if hit
      # Defined in ApplicationHelper
      if sunk && is_game_complete?(tile)  
        game.update_winner(@user)
      end
    else
      game.switch_to_next_players_turn
    end

    ApplicationController.helpers.add_last_move_to_cache(@user.id, tile)
    redirect_to game_index_path(game_id: tile.game_id, hit: hit, sunk: sunk)
  end

end

app/helpers/game_helper.rb
module GameHelper
  def get_most_recent_bomb_class(board, user_board)
    if board.nil? || user_board.nil? || board.id != user_board.id
      return ""
    end

    return "most-recent-bombed"
  end
end

app/views/game/_incorrect_user.html.erb
A game is in progress, but it seems that you're not one of the players within this game

app/views/game/index.html.erb
<%= javascript_include_tag "game" %>

<% if !@game.has_started? %>
  <div>Waiting for player 2...</div>
<% else %>

  
  <% if @game.is_over? %>
    <div class="game-text">Game Over</div>
    <div class="game-text"><%= @user.id == @game.winner_id ? "You" : @game.winner.username %> won!</div>
  
  <% else %> 
    <div class="game-info">
      <div class="game-text">You are playing against <b><%= @opponent_user.username%></b></div>

      <div class="game-text">
        <% if @game.is_players_turn?(@user) %>
          Your turn, please select a location
        <% else %>
          <b><%= @opponent_user.username%></b>'s turn. Waiting...
        <% end %>
      </div>
    </div>

    <div class="status-box">
    <% if !@hit.nil? %>
      <% if @hit %>
        <div class="hit-text">HIT
        <% if @sunk %>
          AND SUNK
        <% end %>

        </div>
      <% else %>
        <div class="miss-text">MISS</div>
      <% end %>
    <% end %>
    </div>
  <% end %>

  <div class="game-panel">
  <div class="game-board">

    <div class="board-text">Opponent's board</div>
  <% @opponent_board.each do |rows| %>

    <div class="tile-row">
    <% rows.each do |tile| %>
      <% if tile.is_bombed %>
        <% if tile.ship_id.nil? %>
          <div class="box water">
            <div class="bombed water-bombed <%= get_most_recent_bomb_class(tile, @last_move[@user.id]) %>">O</div>
          </div>
        <% else %>
          <div class="box opponent-hit">
            <div class="bombed ship-bombed <%= get_most_recent_bomb_class(tile, @last_move[@user.id]) %>">X</div>
          </div>
        <% end %>
      <% else %>
        <% if !@game.is_over? && @game.is_players_turn?(@user) %>
          <div class="clickable-box">
          <%= form_tag(game_fire_missile_path(:tile_id => tile.id), :method => "post") do %>
            <div class="box can-fire opponent-unknown" onclick="$(this).parent().submit()"></div>
          <% end %>
          </div>
        <% else %>
            <div class="box opponent-unknown" /></div>
        <% end %>
      <% end %>
    <% end %>
    </div>
  <% end %>

  </div>


  <div class="game-board">
    <div class="board-text">Your board</div>
  <% @player_board.each do |rows| %>
    <div class="tile-row">
    <% rows.each do |tile| %>

      <% if tile.ship_id.nil? %>
        <div class="box water">
          <% if tile.is_bombed %>
            <div class="bombed water-bombed <%= get_most_recent_bomb_class(tile, @last_move[@opponent_user.id]) %>">O</div>
          <% end %>
        </div>
      <% else %>
        <div class="box player-ship-<%= tile.ship_id % @total_ships %>">
          <% if tile.is_bombed %>
            <div class="bombed ship-bombed <%= get_most_recent_bomb_class(tile, @last_move[@opponent_user.id]) %>">X</div>
          <% end %>
        </div>
      <% end %>
    <% end %>
    </div>
  <% end %>

  </div>
  </div> 



<% end %>

<%= javascript_tag do %>
<% if !@game.is_over? && (!@game.has_started? || !@game.is_players_turn?(@user)) %>
  var timer = setTimeout(function(){
    var url = "/game/index?game_id=<%= @game.id %>"
    window.location.href = url;
  }, 5000);

  $( "#site-name" ).click(function() {
    clearTimeout(timer);
  });
<% end %>
<% end %>